language: php
sudo: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/phpunit --coverage-clover build/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --diff --dry-run --using-cache=no; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then php vendor/bin/php-coveralls -v -x build/clover.xml -o build/clover.json; fi

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "T79AnhNar7G3WV4SAdLs+jlwR95fc+My09gjmSyIA8Wp2i89odVDpXCfMeoMlcbbCCveK1PhzKSzwVpY6409ApAFsSJ6ie4+XIX/0D9Fxg50j/+Fr/DXrEvShy4TaKhDxKLhidTzGMDtLK4TyFSTr5hs44/sqWhMHw50PZ10Egry5HgCFL+42/8j7NlUXl3TD1TTysvJWl7qeayNcZYWcYHP/iMP164kl8XxqSyxRuB7mLDwP3KOQTa9iDDH5sj4bjdraasmaBD+0RBENqjhDj0AO7THSZbprC8ZAKMfO93mldpKIZ3l+2htY94ATvkRnd25sGN/BqpaPGV7ZQirxeWXyeK11XHhp83qtgxw/IyA+6qX1ZU+uu4hKpdoKRn7MzfVuJ4/KYrm+JJdhXCMvCWg2xipc0vo3FUTA3R/T7zrYMM2FydEuewMAsDRDyeGH+MZMHH3OgI75RpVwzvLfoT8rIMCM7/vzVXK+LSU4wQjrUnw4sQxVgAV3KK8FjrdcnfJoyUmmPpb/K/njuBoYu/p2UczKMffjOmGfl/f15QkP+u9dT6JFjNOaCGKf1yvN7EOCvf2GwqBfiSaBD5kPd7VdHFTWMeJc9JiuqoXxBsihwpd84TGOVLJ4iWb6/2wjHTL8wxeZRZZG9BRm5Ri674gNrxL5dwMDv1UtbnNuQc="
